# Generated by Django 5.1.6 on 2025-02-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='origin',
            field=models.CharField(choices=[('Belgium', 'Be'), ('France', 'Fr'), ('United Kingdom', 'Uk')], default='Belgium', max_length=50),
        ),
    ]
