# Generated by Django 5.1.6 on 2025-02-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cover_image',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='stars',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='sub_title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.CharField(default='', max_length=2058),
            preserve_default=False,
        ),
    ]
