# Generated by Django 5.1.6 on 2025-03-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipe_cover_image_recipe_stars_recipe_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(upload_to='', verbose_name='images'),
        ),
    ]
