import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider } from '@mantine/core';

import ReactQueryProvider from "./utils/providers/reactQueryProvider";
import Header from "./components/header";

import '@mantine/core/styles.css'

import '@mantinex/mantine-logo/styles.css'

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <ReactQueryProvider>
          <MantineProvider>
            <Header />
            {children}
          </MantineProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
