import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { Geist, Geist_Mono } from "next/font/google";


import ReactQueryProvider from "./utils/providers/reactQueryProvider";
import Header from "./components/Header";

import '@mantine/core/styles.css'

import '@mantinex/mantine-logo/styles.css'

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <MantineProvider>
            <Header />
            {children}
          </MantineProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
